### PR TITLE
Add my name to the student list

### PR DESCRIPTION
**Pull request by dmyers2004**
Please add my name to the students pull list

### CODE REVIEW

**Comment by jim-parry** [comment]
I can't merge this ... it isn't signed :(

**Comment by jim-parry** [comment]
ps - the "set" for the distance learners should be "pilot"

Can you guess that I am using your PR as an example for my dayschool students in lab?

**Comment by dmyers2004** [comment]
Updated Set and signed off

**Comment by jim-parry** [comment]
I merged your data separately ... a number of other students got their entries in, & yours would no longer merge the way it was. Thank you for being a willing "guinea pig" :)

**Pull request closed without merging**
